# this code works on heroku as is
#
# please set your database name (and settings)

development:
  adapter: sqlite3
  timeout: 5000
  database: db/development.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: sinatras-skeleton
  pool: 5
